# Generated by Django 3.0.5 on 2022-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfonew',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
