# Generated by Django 3.0.5 on 2022-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0003_auto_20220418_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfonew',
            name='total_bill',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
