# Generated by Django 3.0.5 on 2022-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0004_auto_20220602_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_type2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_type3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_type4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_type5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
