# Generated by Django 3.0.5 on 2022-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0005_auto_20220602_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_name3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_name4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_name5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
