# Generated by Django 3.0.5 on 2022-06-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0006_auto_20220602_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicin_detail3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_detail2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_detail4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_detail5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_units2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_units3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_units4',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfonew',
            name='medicine_units5',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
